[metadata]
name = fast-contact-angle-2d
version = 1.0.0
short_description = Package to analyse liquid droplet contact angles on 2d materials from atomistic simulations.
long_description = file: README.md
long_description_content_type = text/markdown
author = Darren Wayne Lim
author_email = dwl38@cam.ac.uk

[options]
packages = find:
python_requires = >=3.7
install_requires =
    numba
    numpy>=2.0.0
    scipy>=1.6.0
    matplotlib
    ase

[options.entry_points]
console_scripts =
    contact_angle = fast_contact_angle_2d.scripts.contact_angle:main
    analyze_surface_dynamics = fast_contact_angle_2d.scripts.analyze_surface_dynamics:main
    droplet_diffusion = fast_contact_angle_2d.scripts.droplet_diffusion:main
