[metadata]
name = droplet-graphene-analysis
version = attr: droplet_graphene_analysis.__version__
short_description = Package to analyse water droplets on graphene surfaces.
long_description = file: README.md
long_description_content_type = text/markdown
author = Darren Wayne Lim
author_email = dwl38@cam.ac.uk

[options]
packages = find:
python_requires = >=3.7
install_requires =
    numba
    rich
    numpy>=2.0.0
    scipy>=1.6.0
    matplotlib
    ase

[options.entry_points]
console_scripts =
    contact_angle = droplet_graphene_analysis.scripts.contact_angle:main
    contact_angle_anisotropic = droplet_graphene_analysis.scripts.contact_angle_anisotropic:main
    make_droplet_movie = droplet_graphene_analysis.scripts.make_droplet_movie:main
    graphene_dynamics = droplet_graphene_analysis.scripts.graphene_dynamics:main
    water_density = droplet_graphene_analysis.scripts.water_density:main
    droplet_diffusion = droplet_graphene_analysis.scripts.droplet_diffusion:main
