[metadata]
name = contact-angle
version = attr: contact_angle.__version__
short_description = Package to analyse water droplets on graphene surfaces.
long_description = file: README.md
long_description_content_type = text/markdown
author = Darren Wayne Lim
author_email = dwl38@cam.ac.uk

[options]
packages = find:
python_requires = >=3.7
install_requires =
    numpy>=2.0.0
    scipy>=1.6.0
    matplotlib
    ase

[options.entry_points]
console_scripts =
    contact_angle = contact_angle.scripts.contact_angle:main
    make_droplet_movie = contact_angle.scripts.make_droplet_movie:main
    graphene_sheet = contact_angle.scripts.plot_graphene:main
    water_density = contact_angle.scripts.water_density:main
