import warnings
import numpy as np
import concurrent.futures
from scipy.spatial import cKDTree
from scipy.linalg import lstsq
from scipy.optimize import curve_fit
from .grid import cast_to_gridsize, generate_grid

#==================================================================================================
# Default parameters for local inclination angle

NN_COUNT = 25    # Number of nearest neighbours to take for local environment

#==================================================================================================

def calc_inclination_angles(
        carbons: np.ndarray,
        cell_xy: np.ndarray | tuple[float, float],
        calc_points: tuple[int, int] | int = 80, *,
        nn_count: int = NN_COUNT,
        max_threads: int = None
        ) -> np.ndarray:
    """This function takes in the coordinates of the carbon atoms of a graphene sheet, and
calculates the local inclination angle of the graphene sheet (wrt the z-axis) at a series of
test points along the xy plane. The inputs are:

    - `carbons`: The Cartesian coordinates of the carbon atoms, either with shape (N_carbon, 3)
    for a single instantaneous frame, or shape (N_frames, N_carbon, 3) for a trajectory.

    - `cell_xy`: The cell parameters along the x- and y-axes, expressed as [cell_x, cell_y].

    - `calc_points`: The number of grid points to calculate the inclination angles at, either
    specified as a tuple of integers (N_x, N_y), or given as a single integer N_x = N_y.

If a single frame is provided, the output is a np.NDArray of shape (N_x, N_y) representing the
instantaneous local inclination angles evaluated at the gridpoints generated by `generate_grid`;
otherwise, if a trajectory is provided, the output is a np.NDArray of shape (N_frames, N_x, N_y)
representing the local inclination angles over the trajectory."""

    if len(carbons.shape) == 3 and carbons.shape[-1] == 3:

        N_frames = carbons.shape[0]
        N_x, N_y = cast_to_gridsize(calc_points)
        results = np.zeros((N_frames, N_x, N_y), dtype=float)
        if max_threads is None or int(max_threads) == 1:
            for f, c in enumerate(carbons):
                results[f] = calc_inclination_angles(c, cell_xy, calc_points, nn_count=nn_count)
        else:
            def work(f, c):
                results[f] = calc_inclination_angles(c, cell_xy, calc_points, nn_count=nn_count)
            pool = concurrent.futures.ThreadPoolExecutor(max_workers=max_threads)
            for f, c in enumerate(carbons):
                pool.submit(work, f, c)
            pool.shutdown(wait=True)
        return results

    elif len(carbons.shape) == 2 and carbons.shape[-1] == 3:

        cell_params = np.array((cell_xy[0], cell_xy[1], 0))
        pos = generate_grid(calc_points, cell_xy)

        N_x = pos.shape[0]
        N_y = pos.shape[1]
        pos = pos.reshape(-1, 2)

        shifts = np.array([[i, j, 0] for i in [-1, 0, 1] for j in [-1, 0, 1]]) * cell_params
        tiled_carbons = (carbons[None, :, :] + shifts[:, None, :]).reshape(-1, 3)
        tree = cKDTree(tiled_carbons[:, :2])
        dists, idxs = tree.query(pos, k=nn_count)

        nearest_neighbours = tiled_carbons[idxs]
        nearest_neighbours[:, :, :2] = nearest_neighbours[:, :, :2] - pos[:, None, :]

        plane_coeffs = np.array([lstsq(np.c_[np.ones(nn_count),
                                                diffs[:, :2],
                                                np.prod(diffs[:, :2], axis=1),
                                                np.square(diffs[:, :2])],
                                        diffs[:, 2])[0][1:3] for diffs in nearest_neighbours])
        cosines = np.power(np.sum(np.square(plane_coeffs), axis=-1) + 1, -0.5)
        angles = np.arccos(cosines) * 180 / np.pi

        return angles.reshape(N_x, N_y)
    
    else:
        raise RuntimeError(f'Unregonized input shape: carbons {carbons.shape}')

#==================================================================================================

def mean_inclination_angles(
        carbons_traj: np.ndarray,
        cell_xy: np.ndarray | tuple[float, float],
        calc_points: tuple[int, int] | int = 80, *,
        nn_count: int = NN_COUNT,
        max_threads: int = None
        ) -> np.ndarray:
    """This function calculates the mean (time-averaged) local inclination angle of the graphene
sheet (wrt the z-axis) at a series of test points along the xy plane. The inputs are:

    - `carbons_traj`: The Cartesian coordinates of the carbon atoms over a trajectory, with shape
    (N_frames, N_carbon, 3).

    - `cell_xy`: The cell parameters along the x- and y-axes, expressed as [cell_x, cell_y].

    - `calc_points`: The number of grid points to calculate the inclination angles at, either
    specified as a tuple of integers (N_x, N_y), or given as a single integer N_x = N_y.

The output is a np.NDArray of shape (N_x, N_y) representing the autocorrelation function, evaluated
at the grid points and tau."""

    angles = calc_inclination_angles(carbons_traj, cell_xy, calc_points, nn_count=nn_count,
                                     max_threads=max_threads)
    return np.mean(angles, axis=0)

#==================================================================================================

def inclination_autocorrelations(
        carbons_traj: np.ndarray,
        cell_xy: np.ndarray | tuple[float, float],
        tau: int = 0,
        calc_points: tuple[int, int] | int = 80, *,
        nn_count: int = NN_COUNT,
        max_threads: int = None
        ) -> np.ndarray:
    """This function calculates the autocorrelation function of the local inclination angle of the
graphene sheet (wrt the z-axis) at a series of test points along the xy plane. The inputs are:

    - `carbons_traj`: The Cartesian coordinates of the carbon atoms over a trajectory, with shape
    (N_frames, N_carbon, 3).

    - `cell_xy`: The cell parameters along the x- and y-axes, expressed as [cell_x, cell_y].

    - `tau`: The time interval to evaluate the autocorrelation function at, in number of frames.

    - `calc_points`: The number of grid points to calculate the inclination angles at, either
    specified as a tuple of integers (N_x, N_y), or given as a single integer N_x = N_y.

The output is a np.NDArray of shape (N_x, N_y) representing the autocorrelation function, evaluated
at the grid points and tau."""

    if tau >= carbons_traj.shape[0]:
        warnings.warn(f'The provided tau ({tau}) is larger than the length of the trajectory ' +
                      f'({carbons_traj.shape[0]})!', RuntimeWarning)
        N_x, N_y = cast_to_gridsize(calc_points)
        return np.zeros((N_x, N_y), dtype=float)
    
    angles = calc_inclination_angles(carbons_traj, cell_xy, calc_points, nn_count=nn_count,
                                     max_threads=max_threads)
    if tau == 0:
        return np.mean(np.square(angles), axis=0)
    return np.mean(angles[:-tau] * angles[tau:], axis=0)
    
#==================================================================================================

def inclination_norm_inf_autocor(
        carbons_traj: np.ndarray,
        cell_xy: np.ndarray | tuple[float, float],
        max_tau: int,
        calc_points: tuple[int, int] | int = 80, *,
        nn_count: int = NN_COUNT,
        max_threads: int = None
        ) -> np.ndarray:
    """This function calculates the limit of the normalized autocorrelation function of the local
inclination angle of the graphene sheet (wrt the z-axis) as the autocorrelation time goes to
infinity, at a series of test points along the xy plane. The inputs are:

    - `carbons_traj`: The Cartesian coordinates of the carbon atoms over a trajectory, with shape
    (N_frames, N_carbon, 3).

    - `cell_xy`: The cell parameters along the x- and y-axes, expressed as [cell_x, cell_y].

    - `max_tau`: The maximum time interval to evaluate the autocorrelation function at, in number
    of frames; this should be no more than 5ps worth of frames.

    - `calc_points`: The number of grid points to calculate the inclination angles at, either
    specified as a tuple of integers (N_x, N_y), or given as a single integer N_x = N_y.

The output is a np.NDArray of shape (N_x, N_y) representing the infinite-time limit of the
normalized autocorrelation function, evaluated at the grid points."""

    N_x, N_y = cast_to_gridsize(calc_points)
    autocorr = np.zeros((max_tau, N_x, N_y), dtype=float)
    angles = calc_inclination_angles(carbons_traj, cell_xy, calc_points, nn_count=nn_count,
                                     max_threads=max_threads)

    autocorr[0] = np.mean(np.square(angles), axis=0)
    for tau in range(1, max_tau):
        autocorr[tau] = np.mean(angles[:-tau] * angles[tau:], axis=0)
    autocorr[:] /= autocorr[0]

    def exp_curve(x, A, k, c):
        return A * np.exp(-k * x) + c

    tau = np.array(range(max_tau))
    result = np.zeros((N_x, N_y), dtype=float)
    for i in range(N_x):
        for j in range(N_y):
            popt, _ = curve_fit(exp_curve, tau, autocorr[:,i,j], p0=(0.3, 1, 0.7))
            result[i,j] = popt[-1]

    return result
