import warnings
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view
from scipy.optimize import curve_fit
from .grid import cast_to_gridsize, generate_grid, smooth_sheet
from .sheet import C_C_DISTANCE

#==================================================================================================
# Default parameters for local inclination angle

CUTOFF_RADIUS = 4.5    # Cutoff radius (in angstroms)

#==================================================================================================

def calc_inclination_angles(
        carbons: np.ndarray,
        cell_xy: np.ndarray | tuple[float, float],
        calc_points: tuple[int, int] | int = 80, *,
        cutoff: float = CUTOFF_RADIUS,
        margin: float = (3 * C_C_DISTANCE)
        ) -> np.ndarray:
    """Calculates the local inclination angles of a graphene sheet (wrt the z-axis) at a series of
    test points along the xy plane, given the coordinates of the carbon atoms.

    Parameters
    ----------
    carbons : ndarray
        The Cartesian coordinates of the carbon atoms, either with shape (N_carbon, 3) for a single
        instantaneous frame; or shape (N_frames, N_carbon, 3) for a trajectory.
    cell_xy : array_like
        The cell parameters along the x- and y-axes, expressed as [cell_x, cell_y].
    calc_points : tuple[int, int] or int, optional
        The number of grid points to calculate the inclination angles at, either specified as a
        tuple of integers (N_x, N_y), or given as a single integer N_x = N_y. Defaults to (80, 80).

    Returns
    -------
    angles : ndarray
        An array of shape (N_x, N_y), representing the instantaneous local inclination angles
        evaluated at the gridpoints generated by `generate_grid`, if a single frame is provided;
        otherwise, if a trajectory is provided, `angles` has shape (N_frames, N_x, N_y)
        representing the local inclination angles over the trajectory.

    Other parameters
    ----------------
    cutoff : float, optional
        The cutoff radius for evaluating the carbon atoms which constitute the local neighbourhood
        of each test point, in angstroms. Defaults to 4.5.
    margin : float, optional
        This parameter is passed to `smooth_sheet`.
    """

    if len(carbons.shape) == 3 and carbons.shape[-1] == 3:

        N_frames = carbons.shape[0]
        N_x, N_y = cast_to_gridsize(calc_points)
        results = np.zeros((N_frames, N_x, N_y), dtype=float)
        for f, c in enumerate(carbons):
            results[f] = calc_inclination_angles(c, cell_xy, calc_points,
                                                 cutoff=cutoff, margin=margin)
        return results

    elif len(carbons.shape) == 2 and carbons.shape[-1] == 3:

        pos = generate_grid(calc_points, cell_xy)
        interp = smooth_sheet(carbons, cell_xy, calc_points, margin=margin)
        points = np.c_[pos[:,:], interp[:,:,None]]
        N_x, N_y = interp.shape

        k_x = int(cutoff * N_x / cell_xy[0])
        k_y = int(cutoff * N_y / cell_xy[1])
        window_size_x = (2 * k_x) + 1
        window_size_y = (2 * k_y) + 1
        padded = np.pad(points, ((k_x, k_x), (k_y, k_y), (0, 0)), mode='wrap')
        padded[:k_x,:,0] -= cell_xy[0]
        padded[-k_x:,:,0] += cell_xy[0]
        padded[:,:k_y,1] -= cell_xy[1]
        padded[:,-k_y:,1] += cell_xy[1]

        patches = sliding_window_view(padded, (window_size_x, window_size_y, 3))
        patches = patches.reshape(N_x * N_y, window_size_x * window_size_y, 3)
        patches -= patches.mean(axis=1, keepdims=True)

        normals = np.empty((N_x * N_y, 3), dtype=float)
        for i, patch in enumerate(patches):
            normals[i] = np.linalg.svd(patch, full_matrices=False)[2][-1]
            normals[i] /= np.linalg.norm(normals[i])

        return (np.arccos(np.abs(normals[:,2])) * 180 / np.pi).reshape(N_x, N_y)
    
    else:
        raise RuntimeError(f'Unregonized input shape: carbons {carbons.shape}')

#==================================================================================================

def mean_inclination_angles(
        carbons_traj: np.ndarray,
        cell_xy: np.ndarray | tuple[float, float],
        calc_points: tuple[int, int] | int = 80,
        **kwargs
        ) -> np.ndarray:
    """Calculates the mean (time-averaged) local inclination angle of the graphene sheet (wrt the
    z-axis) at a series of test points along the xy plane.

    Parameters
    ----------
    carbons_traj : ndarray
        The Cartesian coordinates of the carbon atoms over a trajectory, with shape (N_frames,
        N_carbon, 3).
    cell_xy : array_like
        The cell parameters along the x- and y-axes, expressed as [cell_x, cell_y].
    calc_points : tuple[int, int] or int, optional
        The number of grid points to calculate the inclination angles at, either specified as a
        tuple of integers (N_x, N_y), or given as a single integer N_x = N_y. Defaults to (80, 80).
    **kwargs
        Extra arguments are passed directly to `calc_inclination_angles`.

    Returns
    -------
    mean_angles : ndarray
        An array of shape (N_x, N_y), representing the time-averaged local inclination angles
        evaluated at the gridpoints generated by `generate_grid`.
    """

    angles = calc_inclination_angles(carbons_traj, cell_xy, calc_points, **kwargs)
    return np.mean(angles, axis=0)

#==================================================================================================

def inclination_autocorrelations(
        carbons_traj: np.ndarray,
        cell_xy: np.ndarray | tuple[float, float],
        tau: int = 0,
        calc_points: tuple[int, int] | int = 80,
        **kwargs
        ) -> np.ndarray:
    """Calculates the autocorrelation function of the local inclination angle of the graphene sheet
    (wrt the z-axis) at a series of test points along the xy plane, and a specific time interval.

    Parameters
    ----------
    carbons_traj : ndarray
        The Cartesian coordinates of the carbon atoms over a trajectory, with shape (N_frames,
        N_carbon, 3).
    cell_xy : array_like
        The cell parameters along the x- and y-axes, expressed as [cell_x, cell_y].
    tau : int
        The time interval to evaluate the autocorrelation function at, in number of frames.
    calc_points : tuple[int, int] or int, optional
        The number of grid points to calculate the inclination angles at, either specified as a
        tuple of integers (N_x, N_y), or given as a single integer N_x = N_y. Defaults to (80, 80).
    **kwargs
        Extra arguments are passed directly to `calc_inclination_angles`.

    Returns
    -------
    autocor : ndarray
        An array of shape (N_x, N_y), representing the autocorrelation function evaluated at the
        gridpoints generated by `generate_grid` and tau.
    """

    if tau >= carbons_traj.shape[0]:
        warnings.warn(f'The provided tau ({tau}) is larger than the length of the trajectory ' +
                      f'({carbons_traj.shape[0]})!', RuntimeWarning)
        N_x, N_y = cast_to_gridsize(calc_points)
        return np.zeros((N_x, N_y), dtype=float)
    
    angles = calc_inclination_angles(carbons_traj, cell_xy, calc_points, **kwargs)
    if tau == 0:
        return np.mean(np.square(angles), axis=0)
    return np.mean(angles[:-tau] * angles[tau:], axis=0)
    
#==================================================================================================

def inclination_norm_inf_autocor(
        carbons_traj: np.ndarray,
        cell_xy: np.ndarray | tuple[float, float],
        max_tau: int,
        calc_points: tuple[int, int] | int = 80, *,
        cutoff: float = CUTOFF_RADIUS,
        margin: float = (3 * C_C_DISTANCE)
        ) -> np.ndarray:
    """Calculates the infinite-time limit of the normalized autocorrelation function of the local
    inclination angle of the graphene sheet (wrt the z-axis), at a series of test points along the
    xy plane.

    Parameters
    ----------
    carbons_traj : ndarray
        The Cartesian coordinates of the carbon atoms over a trajectory, with shape (N_frames,
        N_carbon, 3).
    cell_xy : array_like
        The cell parameters along the x- and y-axes, expressed as [cell_x, cell_y].
    max_tau : int
        The maximum time interval to evaluate the autocorrelation function at, in number of frames;
        this should be not much more than 5ps worth of frames.
    calc_points : tuple[int, int] or int, optional
        The number of grid points to calculate the inclination angles at, either specified as a
        tuple of integers (N_x, N_y), or given as a single integer N_x = N_y. Defaults to (80, 80).
    **kwargs
        Extra arguments are passed directly to `calc_inclination_angles`.

    Returns
    -------
    norm_inf_autocor : ndarray
        An array of shape (N_x, N_y), representing the infinite-time limit of the normalized
        autocorrelation function, evaluated at the gridpoints generated by `generate_grid`.
    """

    N_x, N_y = cast_to_gridsize(calc_points)
    autocorr = np.zeros((max_tau, N_x, N_y), dtype=float)
    angles = calc_inclination_angles(carbons_traj, cell_xy, calc_points,
                                     cutoff=cutoff, margin=margin)

    autocorr[0] = np.mean(np.square(angles), axis=0)
    for tau in range(1, max_tau):
        autocorr[tau] = np.mean(angles[:-tau] * angles[tau:], axis=0)
    autocorr[:] /= autocorr[0]

    def exp_curve(x, A, k, c):
        return A * np.exp(-k * x) + c

    tau = np.array(range(max_tau))
    result = np.zeros((N_x, N_y), dtype=float)
    for i in range(N_x):
        for j in range(N_y):
            try:
                popt, _ = curve_fit(exp_curve, tau, autocorr[:,i,j], p0=(0.2, 0.5, 0.8))
                result[i,j] = max(popt[-1], 0.0)
            except RuntimeError:
                result[i,j] = 0.0
    return result
